### ISSUE TITLE
Kanban Board Review for Capstone Project

### ISSUE THREAD

**Issue by Luiscarlosvd** [mrcbq/capstone-rick-and-morty-api#21]
Hello Code reviewer! We are a team of 2 people for this capstone:
Student A - @mrcbq
Student B - @Luiscarlosvd 
Link of Github Project: https://github.com/mrcbq/capstone-rick-and-morty-api/projects/1

**Comment by shella12** [comment]
Hi @Luiscarlosvd and @mrcbq, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Project copies the provided template 👍 
- All tasks are assigned fairly ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
